trigger:
- dev
- master

pool:
  vmImage: 'macOs-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g typescript
  displayName: 'install typescript'

- script: |
    npm install
  displayName: 'npm install workspaces'
