module.exports = {
  updateSetChangeTypes: [
    "Parameter Variable",
    "Test Step Config",
    "Data Source",
    "Decision Input",
    "Email Client Template",
    "Extension Point",
    "Action Inputs",
    "Action Outputs",
    "Flow Inputs",
    "Extended Step Input Variable",
    "Extended Step Output Variable",
    "Navigation Handler",
    "Processor",
    "Recipient Qualifier",
    "Business Rule",
    "Client Script",
    "Email Script",
    "Fix Script",
    "Script Include",
    "UI Action",
    "Context Menu",
    "Embedded List Control",
    "Macro",
    "UI Page",
    "UI Script",
    "Scripted REST Resource",
  ],
};
